# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description_text', models.CharField(max_length=650, verbose_name='video description')),
                ('youtubeKey_text', models.CharField(max_length=20)),
            ],
        ),
    ]
