# Generated by Django 2.0.1 on 2018-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180131_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='amazonPurchaseLink_text',
            field=models.URLField(blank=True, verbose_name='Amazon purchase link'),
        ),
        migrations.AddField(
            model_name='video',
            name='iTunesPurchaseLink_text',
            field=models.URLField(blank=True, verbose_name='Itunes purchase link'),
        ),
        migrations.AddField(
            model_name='video',
            name='sellfyLyricVideoKey_text',
            field=models.CharField(blank=True, max_length=10, verbose_name='The Lyric Video Key for Sellfy'),
        ),
        migrations.AddField(
            model_name='video',
            name='sellfyMusicVideoKey_text',
            field=models.CharField(blank=True, max_length=10, verbose_name='The Music Video Key for Sellfy'),
        ),
        migrations.AddField(
            model_name='video',
            name='sellfyStitchedVideoKey_text',
            field=models.CharField(blank=True, max_length=10, verbose_name='The Combined Music and Lyric Video Key for Sellfy'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_text',
            field=models.CharField(blank=True, max_length=650, verbose_name='video description'),
        ),
    ]
