# Generated by Django 2.0.1 on 2018-02-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20180203_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description_text',
            field=models.TextField(blank=True, verbose_name='video description'),
        ),
    ]
